# Generated by Django 3.0.1 on 2020-12-29 15:10

from django.db import migrations, models
import pp_ag.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('goal', models.TextField(null=True)),
                ('cover_image', models.ImageField(null=True, upload_to='covers')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('image1', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='pictures/', width_field='width_field')),
                ('image2', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='pictures/', width_field='width_field')),
                ('image3', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='pictures/', width_field='width_field')),
                ('image4', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='pictures/', width_field='width_field')),
                ('audio', models.FileField(blank=True, upload_to='audio', validators=[pp_ag.validators.validate_audio_size])),
                ('video', models.FileField(blank=True, upload_to='video', validators=[pp_ag.validators.validate_video_size])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
