# Generated by Django 3.0.1 on 2021-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp_ag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='document',
            field=models.FileField(blank=True, upload_to='document'),
        ),
    ]
